FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    git \
    gosu \
    unzip \
    zip \
    libzip-dev \
    libicu-dev \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libonig-dev \
    libsqlite3-dev \
    pkg-config \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j1 \
    pdo_mysql \
    pdo_sqlite \
    bcmath \
    intl \
    zip \
    gd

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
COPY docker/prod/entrypoint.sh /usr/local/bin/app-entrypoint

RUN chmod +x /usr/local/bin/app-entrypoint

WORKDIR /var/www
ENTRYPOINT ["/usr/local/bin/app-entrypoint"]
